language: php
php:
    - "5.5"
services:
  - mongodb
before_install:
    - sudo apt-get update
    - sudo apt-get install php-pear php5-dev
    - printf "\n" | sudo pecl install mongo
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: echo "Integrating travis"

notifications:
    email:
      - tkannippoyil@suyati.com
